import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Foundation',
      items: ['getting-started', 'tech-stack', 'folder-structure'],
    },
    {
      type: 'category',
      label: 'Application',
      items: ['architecture', 'navigation', 'auth-flow', 'screens'],
    },
    {
      type: 'category',
      label: 'Reference Guide',
      items: [
        {
          type: 'category',
          label: 'Components',
          items: [
            'components',
            'components/text-input',
            'components/password-input',
            'components/submit-button',
            'components/error-text',
            'components/auth-fields-auth-form',
            'components/resend-code-button',
            'components/safeview-auth-layout',
            'components/verify-and-recovery-forms',
          ],
        },
        {
          type: 'category',
          label: 'Hooks',
          items: [
            'hooks',
            'hooks/use-auth-form-state',
            'hooks/use-resend-timer',
            'hooks/use-auth-form',
            'hooks/use-request-password-reset',
            'hooks/use-verify-email',
            'hooks/use-verify-password-reset',
          ],
        },
        'types',
        'services',
      ],
    },
    {
      type: 'category',
      label: 'Generated Reference',
      items: ['reference/index', {type: 'autogenerated', dirName: 'reference/api'}],
    },
    {
      type: 'category',
      label: 'Coming Soon',
      items: [
        'coming-soon/oauth-sso',
        'coming-soon/backend',
        'coming-soon/testing-strategy',
        'coming-soon/deployment',
      ],
    },
  ],
};

export default sidebars;
